//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DossierPatient
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierMedical
    {
        public long IdDossierMedical { get; set; }
        public string Diagnostique { get; set; }
        public Nullable<long> IdPatient { get; set; }
        public string Etat { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
